# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('ad1', models.CharField(max_length=100)),
                ('ad2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('properties', models.CharField(max_length=500)),
            ],
        ),
    ]
